source 'https://rubygems.org'

gem 'rails', '4.1.0'
gem 'sqlite3'

gem 'therubyracer',  platforms: :ruby

gem 'jquery-rails'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'

gem 'omniauth-google-oauth2'
gem 'dotenv-rails'

group :development do
  gem 'pry'
  gem 'pry-nav'
end
